name = "basescriptions-subdomain-router"
main = "index.js"
compatibility_date = "2024-01-01"
account_id = "1e154bc12873eef5423dffecfdeae043"

[[routes]]
pattern = "*.basescriptions.com/*"
zone_name = "basescriptions.com"

[vars]
SUPABASE_URL = "https://fjkmxgseeqmmlqvqcfhv.supabase.co"
BASE_RPC = "https://base-mainnet.g.alchemy.com/v2/YDk7TKMgutp260sJNRhkH"
