name = "basescriptions-indexer"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["* * * * *"]

[vars]
BASE_RPC = "https://base-mainnet.g.alchemy.com/v2/YDk7TKMgutp260sJNRhkH"
